<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LegendaryBlades</AssemblyName>
    <RootNamespace>LegendaryBlades</RootNamespace>
    <Version>1.2.2</Version>
    <AssemblyVersion>1.2.2.0</AssemblyVersion>
    <FileVersion>1.2.2.0</FileVersion>
    <InformationalVersion>1.2.2</InformationalVersion>
    <EnableHarmony>true</EnableHarmony>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>
</Project>
